Added users and organization api
zaletniy/visualization-api pull request #4
Opened 2017-06-05 18:52 UTC by kbhonagiri16

2017-06-05 20:43 UTC, oleksiishyman reviewed
for me codes looks like https://github.com/adejoux/grafanaclient/blob/master/api.go
is there any point in rewriting existing lib, or we can just follow the guide like https://www.djouxtech.net/posts/creating-grafana-dashboards-with-golang/ ?

2017-06-05 20:53 UTC, kbhonagiri16 commented
Oleskii, yes it looks like that but we do not have all required structures and methods mentioned in http://petstore.swagger.io/?url=https://raw.githubusercontent.com/zaletniy/visualization-api/master/doc/visualization-api-1.0.0.yaml so I extended the code base

2017-06-05 22:01 UTC, zaletniy commented on pkg/grafanaclient/test.go
> +package main
Please remove it.
If you need some kind of test please do it with standard test package https://golang.org/pkg/testing/ and build tags https://golang.org/pkg/go/build/#hdr-Build_Constraints, as far as such tests require Grafana instance and can't be called unit, but rather integration.

2017-06-05 22:02 UTC, zaletniy commented on pkg/grafanaclient/api.go
> +// GrafanaError is a error structure to handle error messages in this library
Let us add source where we have borrowed this code.

2017-06-06 21:33 UTC, kbhonagiri16 commented
@oleksiishyman @zaletniy

2017-06-07 00:23 UTC, oleksiishyman commented
github.com/stretchr/testify/assert is not specified in makefile

2017-06-08 19:56 UTC, funrun11 requested changes

2017-06-08 19:56 UTC, zaletniy commented on pkg/grafanaclient/api_test.go
> +package grafanaclient
1. Please mark it with in `integration` tag
// +build integration
2. Create `test-integration` goal in make file where you: spin up docker container with Grafana and predefined config file; run tests against container; delete container

2017-06-08 19:56 UTC, zaletniy commented on pkg/grafanaclient/api_test.go
> +var default_Id = 1
Please use environment variables for this

2017-06-08 19:56 UTC, zaletniy commented
@kbhonagiri16  please address the comments

2017-06-09 01:49 UTC, kbhonagiri16 commented on pkg/grafanaclient/api_test.go
> +package grafanaclient
For 2 I have to build an image with grafana with golang installed right?

2017-06-09 16:58 UTC, kbhonagiri16 commented
@oleksiishyman @zaletniy

2017-06-09 22:18 UTC, funrun11 requested changes

2017-06-09 22:18 UTC, zaletniy commented on Makefile
> +DOCKER_USERNAME=docker_username
DOCKER_USERNAME ?= docker_username

2017-06-09 22:19 UTC, zaletniy commented on Makefile
> +DOCKER_USERNAME=docker_username
Please set if not set, but not overwrite

2017-06-13 17:01 UTC, oleksiishyman commented
I think, that when changes would be ready for merging -> we need to squash all that bunch of commits into one to keep our commit history clear

2017-06-13 18:37 UTC, funrun11 requested changes

2017-06-13 18:37 UTC, zaletniy commented on pkg/grafanaclient/integration_test.go
> +	assert.Nil(t, err, "We are expecting no error and got one")
Please log messages like:
  `assert.Nil(t, err, fmt.Sprintf("We are expecting no error and got one err: %s", err))`

It gives much better output like:

```
--- FAIL: Test_DoLogon (0.00s)
        Error Trace:    integration_test.go:38
	Error:      	Expected nil, but got: &url.Error{Op:"Post", URL:"http://127.0.0.1:3000/login", Err:(*net.OpError)(0xc4200e40f0)}
	Messages:   	We are expecting no error and got one err: Post http://127.0.0.1:3000/login: dial tcp 127.0.0.1:3000: getsockopt: connection refused

```

2017-06-13 19:34 UTC, kbhonagiri16 commented
Done with changes @oleksiishyman @zaletniy

2017-06-13 19:41 UTC, zaletniy commented on pkg/grafanaclient/api.go
> +// GrafanaError is a error structure to handle error messages in this library
:heavy_check_mark:

2017-06-13 19:41 UTC, zaletniy commented on pkg/grafanaclient/test.go
> +package main
:heavy_check_mark:

2017-06-13 19:42 UTC, zaletniy commented on pkg/grafanaclient/api_test.go
> +package grafanaclient
:heavy_check_mark:

2017-06-13 19:43 UTC, zaletniy commented on pkg/grafanaclient/api_test.go
> +var default_Id = 1
@kbhonagiri16

2017-06-13 19:43 UTC, zaletniy commented on Makefile
> +DOCKER_USERNAME=docker_username
@kbhonagiri16

2017-06-13 19:44 UTC, zaletniy commented on pkg/grafanaclient/integration_test.go
> +	assert.Nil(t, err, "We are expecting no error and got one")
:heavy_check_mark:

2017-06-13 19:45 UTC, zaletniy commented
@kbhonagiri16 please squash useless commits and check couple comments above

2017-06-13 19:49 UTC, kbhonagiri16 commented on pkg/grafanaclient/api_test.go
> +var default_Id = 1
This is done check latest

2017-06-13 19:54 UTC, zaletniy commented on pkg/grafanaclient/api_test.go
> +var default_Id = 1
https://gobyexample.com/environment-variables

2017-06-13 20:16 UTC, kbhonagiri16 commented on pkg/grafanaclient/api_test.go
> +var default_Id = 1
https://github.com/zaletniy/visualization-api/pull/4/files#diff-db4f088788a270160bb9d4e0f004ecb1

2017-06-13 20:17 UTC, kbhonagiri16 commented on Makefile
> +DOCKER_USERNAME=docker_username
DONE

2017-06-13 23:39 UTC, zaletniy commented on Makefile
> +DOCKER_USERNAME=docker_username
✔️

2017-06-14 01:14 UTC, kbhonagiri16 commented on pkg/grafanaclient/api_test.go
> +var default_Id = 1
updated

2017-06-14 18:19 UTC, oleksiishyman commented
I don't have any objections, the only thing that has to be resolved is commit squashing

2017-06-14 18:44 UTC, zaletniy commented on pkg/grafanaclient/integration_test.go
> +}
Please use something like this to about any default values
```
var url =  getenv("GRAFANA_URL")
var user = getenv("GRAFANA_USER")
var pass = getenv("GRAFANA_PASS")

func getenv(key string) string {
  value := os.Getenv(key)
  if len(value) == 0 {
    fmt.Printf("Environment variable %s in not defined \n", key)
    os.Exit(1)
  }
  return value
}
```

2017-06-14 19:01 UTC, kbhonagiri16 commented on pkg/grafanaclient/integration_test.go
> +}
Done

2017-06-14 19:24 UTC, funrun11 approved these changes

2017-06-14 19:25 UTC, merged